services:
  quant-ai-mongo-db:
    container_name: quant-ai-mongo-db
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    image: mongo:latest
    ports: [9000:27017]
    volumes: [../data/mongodb-data:/data]
    networks: [quant-ai-mongo-db]

  quant-ai-persistence-middleware-dev:
    container_name: quant-ai-persistence-middleware-dev
    depends_on:
      quant-ai-mongo-db:
        condition: service_healthy
    build:
      context: .
      target: dev
    ports: [9001:8080]
    volumes: [.:/src]
    networks: [quant-ai-persistence-middleware, quant-ai-mongo-db]
    entrypoint: [sleep, infinity]
    init: true

networks:
  quant-ai-mongo-db:
    driver: bridge
  quant-ai-persistence-middleware:
    driver: bridge